
== Led Strip

=== WS2812

WS2812 comes in 5v or 12v.

[NOTE]
====
12v are hooked 3 by 3, which means that programmatically there are 3 times less leds.
====

Each led consumes 0.2W max, to be safe count 20W for 60 led, that is 20W per meter.

I use 5v 150W power supply so that 10m 600 led strip is fine.

==== Wiring

Using Arduino Pro Mini 5v as reference.

As stated in NeoPixel library:

[IMPORTANT]
====
To reduce NeoPixel burnout risk, add 1000 uF capacitor across
pixel power leads, add 300 - 500 Ohm resistor on first pixel's data input
and minimize distance between Arduino and first pixel.  Avoid connecting
on a live circuit...if you must, connect GND first.
====

Then just hook up data pin to one of the pin of arduino.

[NOTE]
====
For 12v strips, make sure not to burn the arduino 5v: don't hook the Vcc !
====

==== Sketches

link:res/WS2812/WS2812-test/WS2812-test.ino[Test]

==== Resources

* https://github.com/adafruit/Adafruit_NeoPixel[Adafruit_NeoPixel]

* LUSTREON 50CM Aluminum Channel Holder For LED Strip Light Bar Under Cabinet Lamp
