= Z-Wave Gateway

== Products

* link:https://aeotec.com/z-wave-usb-stick/[Z-Stick Gen 5]
* link:https://products.z-wavealliance.org/products/21?selectedFrequencyId=1[GreenWave PowerNode NS310-F]

=== Procedures

Here are procedures to setup Z-Wave network:

.Include
* Z-Stick gen5 click 1s -> blue slow blink continuously
* Click "sync" on GreenWave plug -> Stick shows blue long, then blue slow blink continuously
* done

.Exclude
* Z-Stick gen5 click 3s -> orange fast blink continuously
* Click "sync" on GreenWave plug -> Stick shows blue long, then orange fast blink continuously
* done

== Libraries

=== Python 

link:https://github.com/OpenZWave/python-openzwave[]

[source,bash]
====
$ sudo apt-get install --force-yes -y make libudev-dev g++ libyaml-dev
$ pip3 install python_openzwave
$ pip3 install urwid

# Check
$ pyozw_check -i -d /dev/ttyACM0
$ pyozw_check -l -d /dev/ttyACM0 -t 60

# Browse and set Switch
$ pyozw_shell -d /dev/ttyACM0
$$ cd nodes
$$ cd 5
$$ cd User
$$ set Switch to True 
====

=== Controller

link:https://github.com/ruimarinho/docker-openzwave[Docker Controller Panel]

[source,bash]
====
$ docker run --rm -it -p 8090:8090 --device=/dev/ttyACM0 ruimarinho/openzwave
====

Browse to link:http://localhost:8090[] and switch on/off things from UI.