= ZigBee Gateway

== Products

* link:https://phoscon.de/en/conbee2[ConBee II]
* link:https://phoscon.de/en/app/doc[Official doc]

== Software

* link:https://github.com/marthoc/docker-deconz[Docker Deconz]
* link:https://flows.nodered.org/node/node-red-contrib-deconz[NodeRed deconz]
* link:http://dresden-elektronik.github.io/deconz-rest-doc[Deconz API doc]

== Firmware

* link:http://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D[Firmware page]
* link:https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2493[Tips]

**  Unplug the ConBee II
**  Start the above command (with -t parameter)
**  Plugin the ConBee II again

[source,bash]
----
$ sudo GCFFlasher_internal -d /dev/ttyACM2 -t 60 -f deCONZ_ConBeeII_0x26580700.bin.GCF 
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM2 (ConBee II)
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
flashing 160930 bytes: |============error: timeout flashing firmware after 3008 ms
Reboot device /dev/ttyACM2 (ConBee II)
Reboot device /dev/ttyACM2 (ConBee II)
Reboot device /dev/ttyACM2 (ConBee II)
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
flashing 160930 bytes: |==============================|
verify: .
SUCCESS
Wait 10 seconds application starts
----

== Usage

=== Running deCONZ as docker

.Enable dialout
[source,bash]
----
$ sudo usermod -a -G dialout $USER
----

.Run as docker container
[source,bash]
----
$ docker run -d \
    --name=deconz \
    -p 8080:8080 \
    -p 8443:8443 \
    --restart=always \
    -v /etc/localtime:/etc/localtime:ro \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    -e DECONZ_WEB_PORT=8080 \
    -e DECONZ_WS_PORT=8443 \
    -e DECONZ_DEVICE=/dev/ttyZigbee \
    --device=/dev/ttyZigbee \
    marthoc/deconz
----

.Run using docker-compose
[source,yaml]
----
version: "2"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyZigbee
    environment:
      - DECONZ_DEVICE=/dev/ttyZigbee
      - DECONZ_WEB_PORT=40450
      - DECONZ_WS_PORT=40460
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
----

.Browse to link:http://localhost:40450[]

=== Running as native

.Default credentials
delight/delight

=== Tips

Browse to Configuration => Gateway, then Click on Advanced with pressing Shift+Alt

== Deconz API

From link:http://dresden-elektronik.github.io/deconz-rest-doc[Official Deconz API doc]

.Get API token (pre-requisit: browse to Hamburger menu -> Gateway -> Advanced -> Click ‘Authenticate app’)
[source,bash]
----
$ curl -d '{ "devicetype": "Node-RED"}' -H "Content-Type: application/json" -X POST http://192.168.1.46:40450/api
...
# Token is returned
----

.List sensors
[source,bash]
----
$ curl -H "Content-Type: application/json" http://192.168.1.46:40450/api/XXAAXX/sensors | jq .
...
----

.Touchlink
[source,bash]
----
$ curl -H "Content-Type: application/json" -X POST http://192.168.1.46:40450/api/9598E1143E/touchlink/scan
----

== Deconz WebSocket API

.WebSocket configuration
[source,bash]
----
$ curl -H "Content-Type: application/json" http://192.168.1.46:40450/api/XXAAXX/config | jq .

{
  "UTC": "2020-08-23T18:31:17",
  "apiversion": "1.16.0",
  "backup": {
    "errorcode": 0,
    "status": "idle"
  },
  "bridgeid": "XOXOXOXOXO",
  "datastoreversion": "93",
  "devicename": "RaspBee",
  "dhcp": true,
...
  "uuid": "606b08d1-5f14-4032-86cc-xxxxxx",
  "websocketnotifyall": true,
  "websocketport": 40460,
  "whitelist": {
    "XOXOXOXOXO": {
      "create date": "2020-08-22T18:40:34",
      "last use date": "2020-08-22T18:40:34",
      "name": "Node-RED"
    },
 ...
  },
  "zigbeechannel": 15
}
----

.WebSocket event listen (link:http://dresden-elektronik.github.io/deconz-rest-doc/websocket/[sample])
[source,js]
----
const WebSocket = require('ws');

const host = '192.168.1.46';
const port = 40460;

const ws = new WebSocket('ws://' + host + ':' + port);

ws.onmessage = function(msg) {
    console.log(JSON.parse(msg.data));
}
----


= References

.Custom ZigBee projects
* link:https://github.com/formtapez/ZigUP/[ZigUP]