= IoT-Tools project 
:toc: macro
:hardbreaks:

ifdef::env-github[]
:binariesdir: /project/src/main/adoc/binaries
:giturl: 
:imagesdir: /project/src/main/adoc/images
//:sectlinks:
//:sectnums:
// Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://github.com/kalemena/iot-tools/workflows/Pipeline/badge.svg[GitHub Build] image:https://images.microbadger.com/badges/version/kalemena/arduino.svg[Docker Version, link=https://microbadger.com/images/kalemena/arduino] image:https://images.microbadger.com/badges/image/kalemena/arduino.svg[Docker Hub, link=https://hub.docker.com/r/kalemena/arduino/tags]

toc::[]

Internet Of Things starts in general with sensors and micro-controllers.

This repository lists information to help setting up and hooking up Atmega (Arduino, Arduino Nano, Arduino Pro Mini), ESP8266 or ESP32.

Sorry if references are ommited.
Resources are also gathered from external sites, sometimes with more details. 

//ifdef::env-github,confluencePublisherVersion[]

<<<

== Docker image

The docker image link:https://hub.docker.com/r/kalemena/arduino[kalemena/arduino] contains pre-installed Arduino IDE.

The image is setup with many libraries, plus subset of Arduino-compatible boards, including ESP8266 and ESP32.

<<<

// ==== Boards Layout

// GitHub-display
ifdef::env-github[]
== Board Layouts

There are tons of boards, and this repo lists only few layouts.
See link:/src/main/adoc/pinouts/readme.adoc[here]

endif::[]

// non-GitHub
ifndef::env-github[]

:leveloffset: +1

include::categories/pinouts/readme.adoc[here]

:leveloffset: -1

endif::[]

// Setups

== Manual Setup

For all flavors of Atmega, just download Arduino IDE.

ifdef::env-github[]

For ESP specifics:

* link:/src/main/adoc/categories/setups/setup-esp8266-arduino.adoc[Setup ESP 8266 Arduino IDE]
* link:/src/main/adoc/categories/setups/setup-esp32-arduino.adoc[Setup ESP 32 Arduino IDE]
* link:/src/main/adoc/categories/low-power/readme.adoc[Low-power tips]

endif::[]

ifndef::env-github[]

:leveloffset: +2

include::categories/setups/setup-esp8266-arduino.adoc[Setup ESP 8266 Arduino IDE]

include::categories/setups/setup-esp32-arduino.adoc[Setup ESP 32 Arduino IDE]

include::categories/low-power/readme.adoc[Low-power tips]

:leveloffset: -2

endif::[]
